ARG REPOSITORY=docker.osdc.io
ARG BUILDER_TAG=2.2.0
FROM ${REPOSITORY}/ncigdc/base-u22.04-builder:${BUILDER_TAG} AS builder

ARG VERSION

ENV URL=https://github.com/alexdobin/STAR/archive/${VERSION}.tar.gz

RUN wget $URL \
        && tar -xzf ${VERSION}.tar.gz \
        && rm ${VERSION}.tar.gz \
        && cp STAR-${VERSION}/bin/Linux_x86_64_static/STAR /usr/local/bin/STAR \
        && rm -rf STAR-${VERSION}

